server:
  port: 8080

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password: root

item:
  max: 3
  once: 10
  maxCnt: 3
  maxQty: 3
