version: 0.0
os: linux
files:
  - source: /
    destination: /opt/login-service
    overwrite: yes
permissions:
  - object: /opt/login-service/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: run_java.sh
